# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 372319fed70cd03d41e9a317e188670446d7ccc699c1c3d022133047a200c96d2d602197ec098ccdede5871445dfad1bb70a780fb5a0c5533ee870b023153877

test:
  secret_key_base: e2cee65377973adbe05b19e8f0f7f55560527e536587d6d9efa473f27525709b6c65815b50145ca794429a1d1afdbddfa92ba0f6540b9cddd7b5eb8164194f59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
